c-api/intro.po 번역
python/python-docs-ko pull request #634
Opened 2020-12-06 07:21 UTC by NovemberOscar

생각보다 늦게 완료되었습니다 😥

2020-12-06 07:31 UTC, flowdas commented
와! 감사합니다. 안그래도 작업이 거의 된 것 같은데, 혹 어떤 어려움이 있으신가해서 연락 한번 드리려고 했습니다. 그런데 그동안 브랜치가 3.9로 옮겨갔습니다. 3.9 브랜치로 rebase 후에 3.9 브랜치로 PR 부탁드립니다. 혹시 이 절차가 잘 진행되지 않는다거나 다른 어려움이 있으시면 알려주세요. 제가 어떻게 해 보겠습니다.

2020-12-06 08:37 UTC, NovemberOscar commented
3.9 올라오면서 바뀐게 없는지 리베이스는 간단하게 되었습니다 :) 호기롭게 시작한 것에 비해 인터럽트가 많이 걸려서 3.9 나오기 전까지 작업을 못 마친게 아쉽네요

2020-12-08 00:36 UTC, flowdas commented
감사합니다. 사실은 3.9로 올라오면서 Py_UNREACHABLE() 부분이 조금 바뀌고 내용이 추가되었습니다. 그래서 리베이스 후에 이 영역의 메시지가 약간 어긋나있고, 번역되지 않은 메시지도 3개 남아있게 되었습니다. 손보실 수 있으실까요?

2020-12-08 01:30 UTC, NovemberOscar commented
네네 오늘 저녁에 한번 보도록 하겠습니다

2020-12-11 00:13 UTC, flowdas requested changes
수고하셨습니다. 몇가지 사소한 에러에 대해 코멘트 남깁니다.

2020-12-11 00:13 UTC, flowdas commented on c-api/intro.po
> +"있으며, 허수를 표현하기 위해 사용되는 구조체 형도 있습니다. 이러한 형들은 해당 형들을 사용하는 함수와 함께 다뤄질 것입니다."
"허수" 가 아니라 "복소수" 인듯합니다.

2020-12-11 00:13 UTC, flowdas commented on c-api/intro.po
> +msgstr "많은 어설션이 사전과 집합 구현에 추가됩니다. 또한 집합 객체는 :meth:`test_c_api` 메소드가 추가됩니다."
dictionary 도 용어집에 등장하는 것이라 "딕셔너리"로 통일하고 있습니다.

2020-12-11 00:42 UTC, NovemberOscar commented on c-api/intro.po
> +"호출해야 하므로 참조 횟수를 증가시키는 매크로보다 상당히 복잡합니다. 할당 해제자는 객체의 유형 구조체에 포함된 함수 포인터입니다."
L929 의 `A full list of the various types of debugging builds...` 의 type 은 용어집에서 설명하는 type 의 범주가 아닌것 같아 '유형' 을 유지했는데 괜찮을까요?

2020-12-11 00:42 UTC, NovemberOscar commented on c-api/intro.po
> +" 렉터리 입니다."
수정했습니다. 감사합니다.

2020-12-11 00:42 UTC, NovemberOscar commented on c-api/intro.po
> +"헤더를 인클루드 하기 위해선 두 디렉터리 모두 (두 디렉토리가 다를 경우) 컴파일러의 검색 패스에 추가하십시오. 부모 디렉터리를 "
수정했습니다. 감사합니다.

2020-12-11 00:42 UTC, NovemberOscar commented on c-api/intro.po
> +"코드 경로가 매우 가능성이 낮지만 예외적인 경우에 도달할 수 있는 경우, 이 매크로를 사용해서는 안됩니다. 예를 들어, 메모리 "
수정했습니다. 감사합니다.

2020-12-11 00:42 UTC, NovemberOscar commented on c-api/intro.po
> +"함수의 미사용 인자에 사용하여 컴파일러 경고를 무시하십시오. 예시: ``int func(int a, int Py_UNUSED(b))"
네 "무시합니다" 가 조금 더 자연스러운 듯 합니다. 수정했습니다. 감사합니다.

2020-12-11 00:42 UTC, NovemberOscar commented on c-api/intro.po
> +" 할당이 해제될 수 있습니다. (서로를 참조하는 객체에 대해 분명한 문제점이 있으나 현재 해결책은 \"그러지 마세요.\" 입니다.)"
수정했습니다. 감사합니다.

2020-12-11 00:42 UTC, NovemberOscar commented on c-api/intro.po
> +"호출자에게 넘길때 발신자는 *새로운* 참조를 받는다고 합니다. 소유권이 옮겨지지 않을 때 호출자는 참조를 *빌린다* 라고 합니다. "
수정했습니다. 감사합니다.

2020-12-11 00:43 UTC, NovemberOscar commented on c-api/intro.po
> +"있으며, 허수를 표현하기 위해 사용되는 구조체 형도 있습니다. 이러한 형들은 해당 형들을 사용하는 함수와 함께 다뤄질 것입니다."
수정했습니다. 감사합니다.

2020-12-11 00:43 UTC, NovemberOscar commented on c-api/intro.po
> +msgstr "많은 어설션이 사전과 집합 구현에 추가됩니다. 또한 집합 객체는 :meth:`test_c_api` 메소드가 추가됩니다."
수정했습니다. 감사합니다.

2020-12-11 00:57 UTC, NovemberOscar commented on c-api/intro.po
> +msgstr "파일 인클루드"
[위키백과 - 헤더 파일](https://ko.wikipedia.org/wiki/%ED%97%A4%EB%8D%94_%ED%8C%8C%EC%9D%BC) 에 따르면 헤더 파일을 "인클루드 파일" 로도 부른다는 것을 발견해 "인클루드 파일" 로 수정했습니다

2020-12-11 21:43 UTC, flowdas commented on c-api/intro.po
> +"호출해야 하므로 참조 횟수를 증가시키는 매크로보다 상당히 복잡합니다. 할당 해제자는 객체의 유형 구조체에 포함된 함수 포인터입니다."
예, 그 부분은 용어집의 type 을 뜻하지 않는듯합니다.

2020-12-11 22:58 UTC, merged